config/routes.rb
Rails.application.routes.draw do
  resources :emails
  get 'codeform/pics'
  get 'codeform/texts'
  resources :textanimations
  resources :picanimations
  resources :pics
  resources :texts
  resources :rooms
  resources :messages do
    member do
      get "css"
    end
  end
  devise_for :users
  root "rooms#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :pics
  accepts_nested_attributes_for :pics, allow_destroy: true
  has_many :texts
  accepts_nested_attributes_for :texts, allow_destroy: true
  def image=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
    end
    write_attribute(:image, uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
  def music=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
    end
    write_attribute(:music, uploaded_io.original_filename)
  end
  def music
    read_attribute(:music)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy css]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
    @text=Text.new(message_id:@message.id,fond:"#ffffff",duration:3, delay:0)
    @pic=Pic.new(message_id:@message.id,width:100,height:100,duration:3,delay:0)
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def css
    #if @message.pics[0]
    #  @message.pics[0].picanimations.new(percent:0)
    #end
    #if @message.texts[0]
    #  @message.texts[0].textanimations.new(percent:0)
    #end
  end
  def edit
    

  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        ChatJob.perform_now(@message)
        #format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        #format.json { render :show, status: :created, location: @message }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        MessageJob.perform_now(@message)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:sent_by, :body,:user_id,:room_id, :height, :width, :bodyx, :bodyy,:image,:music,:texts_attributes=>{},:pics_attributes=>{})
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_cssmessage.html.erb
#move<%=message.id%> {
        <%if params[:controller] == "messages" && params[:action] != "edit"%>
          display:none;
        <%end%>
                       height: 10px;
                                              width: 10px;
                                                                             position: absolute;
                                                                                                            top: 100%;
                                                                                                                                           left: 100%;
                                                                                                                                                                                                  background: green;
                                                                                                                                                                                                                                                               }
      .speaker,.mytext, #mybody<%=message.id%> {
        background:white;
        position:absolute;
      }
      <%if !["css","edit"].include?(params[:action])%>
      <%message.texts.each do |pic|%>

        <%if pic.textanimations.length > 0 %>
        .mytextanimation<%=pic.id%> {
          animation-duration: <%=pic.duration || 3%>s;
          animation-delay: <%=pic.delay || 0%>s;
          animation-name: textanimation<%=pic.id%>;
        }
      @keyframes textanimation<%=pic.id%> {
        <%pic.textanimations.each do |x|%>
          <%=x.percent%>% {
            transform: translateX(<%=x.translatex.to_i%>px) translateY(<%=x.translatey.to_i%>px) rotate(<%=x.rotate%>deg);
            color: <%=x.color||"#ffffff"%>;
                      }
        <%end%>
      }
        <%end%>

      <%end%>
      <%message.pics.each do |pic|%>

        <%if pic.picanimations.length > 0%>
        .mypicanimation<%=pic.id%> {
          animation-duration: <%=pic.duration || 3%>s;
          animation-delay: <%=pic.delay || 0%>s;
          animation-name: picanimation<%=pic.id%>;
        }
      @keyframes picanimation<%=pic.id%> {
        <%pic.picanimations.each do |x|%>
          <%=x.percent%>% {
            transform: translateX(<%=x.translatex.to_i%>px) translateY(<%=x.translatey.to_i%>px) rotate(<%=x.rotate%>deg);
            color: <%=x.color||"#ffffff"%>;
                      }
        <%end%>
      }
        <%end%>

      <%end%>
      <%end%>
                                                                                                                                                                                                                                                           #mypic<%=message.id%>{

                                                                                                                                                                                                                                                               border:1px solid black;
                                                                                                                                                                                                                                                                 position:relative;
                                                                                                                                                                                                                                                                   width:<%=message.width%>px;
                                                                                                                                                                                                                                                                     height:<%=message.height%>px;
                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                   #mybody<%=message.id%> {
                                                                                                                                                                                                                                                                       position:absolute;
                                                                                                                                                                                                                                                                        left:<%=message.bodyx%>px;
                                                                                                                                                                                                                                                                          top:<%=message.bodyy%>px;
                                                                                                                                                                                                                                                                          }

app/views/messages/_form.html.erb
<%= form_with(model: message,html:{onsubmit:"$.ajax({url:this.action,type:this.method,data:$(this).serialize(),success:function(data){console.log(data);}});return false;"}) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sent_by, style: "display: block" %>
    <%= form.text_field :sent_by %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>

  </div>
    <%= form.hidden_field :user_id %>
    <%= form.hidden_field :room_id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_formedit.html.erb
<div id="myid1"><%=message.id%></div>
<%= form_with(model: message,html:{id:"frm-editmsg"}) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sent_by, style: "display: block" %>
    <%= form.text_field :sent_by %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>

  </div>
  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.number_field :height,step:"0.01" %>

  </div>
  <div>
    <%= form.label :width, style: "display: block" %>
    <%= form.number_field :width,step:"0.01"%>

  </div>
  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>

  </div>
  <div>
    <%= form.label :music, style: "display: block" %>
    <%= form.file_field :music %>

  </div>
  <div class="mytextsandpics">
  <div class="mytexts">

    <%=form.fields_for :texts do |f|%>
    <table>
        <tr class="tabletext">
          <td></td>
          <td>text #<%=f.index + 1%></td>
      </tr>
        <tr class="tabletext">
          <td>content</td>
          <td><%=f.text_field :content,onkeyup:"text_#{f.object.id}.innerHTML=this.value;"%></td>
        <%=f.hidden_field :x, id: "message_texts_attributes_#{f.object.id}_x"%>
        <%=f.hidden_field :y, id: "message_texts_attributes_#{f.object.id}_y"%>
      </tr>
        <tr class="tabletext">
          <td>font size</td>
          <td><%=f.number_field :size,onkeyup:"text_#{f.object.id}.style.fontSize=this.value+'px';"%></td>

      </tr>
        <tr class="tabletext">
          <td>font color</td>
          <td><%=f.color_field :color,onchange:"text_#{f.object.id}.style.color=this.value;",onkeyup:"text_#{f.object.id}.style.color=this.value;"%></td>

      </tr>
        <tr class="tabletext">
          <td>font weight</td>
          <td><%=f.number_field :weight,onkeyup:"text_#{f.object.id}.style.fontWeight=this.value;"%></td>

      </tr>
        <tr class="tabletext">
          <td>couleur fond</td>
          <td><%=f.color_field :fond,onchange:"text_#{f.object.id}.style.backgroundColor=this.value;",onkeyup:"text_#{f.object.id}.style.backgroundColor=this.value;"%></td>

      </tr>
        <tr class="tabletext">
          <td>fond transparent</td>
          <td> 
              <%= f.label :transparent %><br />
              <%= f.label :transparent, "Oui", value: "true"  %>
              <%= f.radio_button :transparent, true,onchange:"this.checked ? (text_#{f.object.id}.style.backgroundColor='transparent') : (text_#{f.object.id}.style.backgroundColor=message_texts_attributes_#{f.index}_fond.value);" %>
              <%= f.label :transparent, "Non", value: "false" %>
              <%= f.radio_button :transparent, false,onchange:"message_texts_attributes_#{f.index}_transparent_true.checked === '1' ? (text_#{f.object.id}.style.backgroundColor='transparent') : (text_#{f.object.id}.style.backgroundColor=message_texts_attributes_#{f.index}_fond.value);" %>
            </td>

      </tr>
        <tr class="tabletext">
          <td>z-index</td>
          <td><%=f.number_field :zindex,onchange:"text_#{f.object.id}.style.zIndex=this.value;",onkeyup:"text_#{f.object.id}.style.zIndex=this.value;",max:99%></td>

      </tr>
    </table>
    <%=f.fields_for :textanimations do |ff|%>
    <table>
        <tr class="tabletext">
          <td>&ensp;</td>
          <td>text animation #<%=ff.index + 1%></td>
      </tr>
    </table>
    <%end%>
    <%end%>

  </div>
  <div class="mypics">

    <%=form.fields_for :pics do |f|%>
    <table>
        <tr class="tabletext">
          <td>&ensp;</td>
          <td>pic #<%=f.index + 1%></td>
      </tr>
      <td><%=f.hidden_field :x,id:"message_pics_attributes_#{f.object.id}_x"%>
          <td><%=f.hidden_field :y,id:"message_pics_attributes_#{f.object.id}_y"%>
        <tr class="tabletext">
          <td><%=f.label :width%>
          <td><%=f.text_field :width,onchange:"pic_#{f.object.id}.style.width=this.value;"%>
      </tr>
        <tr class="tabletext">
          <td><%=f.label :height%>
          <td><%=f.text_field :height,onchange:"pic_#{f.object.id}.style.width=this.value;"%>

      </tr>
        <tr class="tabletext">
          <td>couleur fond</td>
          <td><%=f.color_field :fond,onchange:"pic_#{f.object.id}.style.backgroundColor=this.value;",onkeyup:"pic_#{f.object.id}.style.backgroundColor=this.value;"%></td>

      </tr>
        <tr class="tabletext">
          <td>fond transparent</td>
          <td> 
              <%= f.label :transparent %><br />
              <%= f.label :transparent, "Oui", value: "true"  %>
              <%= f.radio_button :transparent, true,onchange:"this.checked ? (pic_#{f.object.id}.style.backgroundColor='transparent') : (pic_#{f.object.id}.style.backgroundColor=message_pics_attributes_#{f.index}_fond.value);" %>
              <%= f.label :transparent, "Non", value: "false" %>
              <%= f.radio_button :transparent, false,onchange:"message_pics_attributes_#{f.index}_transparent_true.checked === '1' ? (pic_#{f.object.id}.style.backgroundColor='transparent') : (pic_#{f.object.id}.style.backgroundColor=message_pics_attributes_#{f.index}_fond.value);" %>
            </td>

      </tr>
        <tr class="tabletext">
          <td>z-index</td>
          <td><%=f.number_field :zindex,onchange:"pic_#{f.object.id}.style.zIndex=this.value;",onkeyup:"pic_#{f.object.id}.style.zIndex=this.value;",max:99%></td>

      </tr>
    </table>
    <%=f.fields_for :picanimations do |ff|%>
    <table>
        <tr class="tabletext">
          <td>&ensp;</td>
          <td>pic animation #<%=ff.index + 1%></td>
      </tr>
    </table>
    <%end%>
    <%end%>

  </div>
  </div>
  <%=render message%>
<script>
  function editmypicwidth(){
mypic.style.width=String(this.value)+'px';
    }
  function editmypicheight(){
mypic.style.height=String(this.value)+'px';
    }
</script>
    <%= form.hidden_field :user_id %>
    <%= form.hidden_field :room_id %>
    <%= form.hidden_field :bodyx %>
    <%= form.hidden_field :bodyy%>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/css.html.erb
<h1>Editing message</h1>
<%=form_with do |ff|%>
                                                                                                                                                                                                                                                                                                                                                     <table>
     <tr>
       <td>
           <%= ff.label :percent, style: "display: block" %>
                   <%= ff.range_field :percent,list:"values" %>


                               <datalist id="values">
                                                       <option class="mytextorpic" value="0" label="début"></option>
                                                                                     <option class="mytextorpic" value="25" label="vers le début"></option>
                                                                                                                           <option class="mytextorpic" value="50" label="milieu"></option>
                                                                                                                                                                         <option class="mytextorpic" value="75" label="vers la fin"></option>
                                                                                                                                                                                                                               <option class="mytextorpic" value="100" label="fin"></option>
                                                                                                                                                                                                                                                                                         </datalist>

                                                                                                                                                                                                                                                                                                                                                     </td>
       <td>
           <%= ff.label :rotate, style: "display: block" %>
                   <%= ff.range_field :rotate,list:"rotatevalues",value:0,min:-365,max:365 %>


                               <datalist id="rotatevalues">
                                                       <option class="mytextorpic" value="-365" label="rotate <-"></option>
                                                                                     <option class="mytextorpic" value="0" label="don't rotate"></option>
                                                                                     <option class="mytextorpic" value="365" label="rotate ->"></option>
                                                                                                                                                                                                                                                                                         </datalist>

                                                                                                                                                                                                                                                                                                                                                     </td>
                                                                                                                                                                                                                                                                                                                                                     </tr>
                                                                                                                                                                                                                                                                                                                                                     </table>

                                                                                                                                                                                                                                                                                                                                                   <%end%>

<%= render "formcss", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "formedit", message: @message %>

<br>

<div>
  <%= link_to "animations css", css_message_path(@message.id) %> |
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>
  <div data-chat-room="<%=@message.room.name%>">
              </div>
<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>
<button id="myBtnemail">Envoyer à un(e) ami(e)</button>

<!-- The Modal -->
<div id="myModalemail" class="modalemail">

      <!-- Modal content -->
            <div class="modal-contentemail">
                          <span class="closeemail">&times;</span>
                                      <div><%= render "emails/form",email: Email.new(message_id:@message.id) %></div>
                                                        </div>

</div>
<button id="myBtnpic">Ajouter une image</button>

<!-- The Modal -->
<div id="myModalpic" class="modalpic">

      <!-- Modal content -->
            <div class="modal-contentpic">
                          <span class="closepic">&times;</span>
                                      <div><%= render "pics/form",pic: @pic %></div>
                                                        </div>

</div>
<button id="myBtn">Ajouter un texte</button>

<!-- The Modal -->
<div id="myModal" class="modal">

      <!-- Modal content -->
            <div class="modal-content">
                          <span class="close">&times;</span>
                                      <div><%= render "texts/form",text: @text %></div>
                                                        </div>

</div>

<%= render @message %>
<%if @message.music%>
    <audio src="/uploads/<%=@message.music%>" type="audio/mp3" id="myaudio" autoplay=""/>
<%end%>
  <div data-chat-room="<%=@message.room.name%>">
          </div>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>