config/routes.rb
Rails.application.routes.draw do
  resources :emails
  get 'codeform/pics'
  get 'codeform/texts'
  resources :textanimations
  resources :picanimations
  resources :pics
  resources :texts
  resources :rooms
  resources :messages do
    member do
      get "css"
    end
  end
  devise_for :users
  root "rooms#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/picanimation.rb
class Picanimation < ApplicationRecord
  belongs_to :pic
end

app/controllers/picanimations_controller.rb
class PicanimationsController < ApplicationController
  before_action :set_picanimation, only: %i[ show edit update destroy ]

  # GET /picanimations or /picanimations.json
  def index
    @picanimations = Picanimation.all
  end

  # GET /picanimations/1 or /picanimations/1.json
  def show
  end

  # GET /picanimations/new
  def new
    @picanimation = Picanimation.new
  end

  # GET /picanimations/1/edit
  def edit
  end

  # POST /picanimations or /picanimations.json
  def create
    @picanimation = Picanimation.new(picanimation_params)

    respond_to do |format|
      if @picanimation.save
        format.html { redirect_to picanimation_url(@picanimation), notice: "Picanimation was successfully created." }
        format.json { render :show, status: :created, location: @picanimation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picanimation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /picanimations/1 or /picanimations/1.json
  def update
    respond_to do |format|
      if @picanimation.update(picanimation_params)
        format.html { redirect_to picanimation_url(@picanimation), notice: "Picanimation was successfully updated." }
        format.json { render :show, status: :ok, location: @picanimation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picanimation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picanimations/1 or /picanimations/1.json
  def destroy
    @picanimation.destroy

    respond_to do |format|
      format.html { redirect_to picanimations_url, notice: "Picanimation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picanimation
      @picanimation = Picanimation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picanimation_params
      params.require(:picanimation).permit(:pic_id, :percent, :translatex, :translatey, :rotate, :color)
    end
end

app/helpers/picanimations_helper.rb
module PicanimationsHelper
end

app/views/picanimations/_form.html.erb
<%= form_with(model: picanimation) do |form| %>
  <% if picanimation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(picanimation.errors.count, "error") %> prohibited this picanimation from being saved:</h2>

      <ul>
        <% picanimation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.hidden_field :pic_id %>


  <div>
    <%= form.label :percent, style: "display: block" %>
    <%= form.range_field :percent,list:"values" %>


    <datalist id="values">
        <option class="mytextorpic" value="0" label="début"></option>
        <option class="mytextorpic" value="25" label="vers le début"></option>
        <option class="mytextorpic" value="50" label="milieu"></option>
        <option class="mytextorpic" value="75" label="vers la fin"></option>
        <option class="mytextorpic" value="100" label="fin"></option>
    </datalist>

  </div>

  <div>
    <%= form.label :translatex, style: "display: block" %>
    <%= form.text_field :translatex %>
  </div>

  <div>
    <%= form.label :translatey, style: "display: block" %>
    <%= form.text_field :translatey %>
  </div>

  <div>

    <%= form.range_field :rotate, min:"-365", max:365,list:"valuesrotate" %>
    <%= form.label :rotate, style: "display: block" %>
    <datalist id="valuesrotate">
        <option class="mytextorpic" value="-365" label="rotate <-"></option>
        <option class="mytextorpic" value="0" label="don't rotate"></option>
        <option class="mytextorpic" value="365" label="rotate ->"></option>
    </datalist>

  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/picanimations/_picanimation.html.erb
<div id="<%= dom_id picanimation %>">
  <p>
    <strong>Pic:</strong>
    <%= picanimation.pic_id %>
  </p>

  <p>
    <strong>Percent:</strong>
    <%= picanimation.percent %>
  </p>

  <p>
    <strong>Translatex:</strong>
    <%= picanimation.translatex %>
  </p>

  <p>
    <strong>Translatey:</strong>
    <%= picanimation.translatey %>
  </p>

  <p>
    <strong>Rotate:</strong>
    <%= picanimation.rotate %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= picanimation.color %>
  </p>

</div>

app/views/picanimations/edit.html.erb
<h1>Editing picanimation</h1>

<%= render "form", picanimation: @picanimation %>

<br>

<div>
  <%= link_to "Show this picanimation", @picanimation %> |
  <%= link_to "Back to picanimations", picanimations_path %>
</div>

app/views/picanimations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Picanimations</h1>

<div id="picanimations">
  <% @picanimations.each do |picanimation| %>
    <%= render picanimation %>
    <p>
      <%= link_to "Show this picanimation", picanimation %>
    </p>
  <% end %>
</div>

<%= link_to "New picanimation", new_picanimation_path %>

app/views/picanimations/new.html.erb
<h1>New picanimation</h1>

<%= render "form", picanimation: @picanimation %>

<br>

<div>
  <%= link_to "Back to picanimations", picanimations_path %>
</div>

app/views/picanimations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @picanimation %>

<div>
  <%= link_to "Edit this picanimation", edit_picanimation_path(@picanimation) %> |
  <%= link_to "Back to picanimations", picanimations_path %>

  <%= button_to "Destroy this picanimation", @picanimation, method: :delete %>
</div>